# Valid login request
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "kylee",
  "password": "helloreact"
}

########################
# Valid login request
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "kylee1",
  "password": "hellonode"
}