version: "3.8"

services: 
  app:
    image: hello-front-dev
    build:
      context: . 
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: hello-front-dev
  
  debug-helper:
    image: busybox

  nginx:
    image: nginx:1.20.1
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro # ro stands for read-only
    ports:
    - 8080:80
    container_name: reverse-proxy