version: "3.8"

services: 
  app:
    image: hello-front-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-frontend # This will name the container hello-front-dev
